# Generated by Django 2.0 on 2018-04-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20180407_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
